[server]
ip = "auto"
port = 8080
timeout = 2

[data]
save = false
path = "data/"
date_format = "%d-%m-%Y_%H-%M-%S"

[figure]
save = false
path = "figures/"
format = "png"
date_format = "%d-%m-%Y_%H-%M-%S"

[colors]
red = "#cf7171"
green = "#dbe8c1"
blue = "#aecdd2"
yellow = "#fadf7f"
purple = "#c696bc"
black = "#4d5359"

[model]
targets = ["fx", "fy", "fz", "mx", "my", "mz"]
features = ["s0", "s1", "s2", "s3"]
n_inducing_points = 32
kernel = "rq"
mean = "constant"
required_samples = 1024
max_samples = 2048
epochs = 10
batch_size = 32
lr = 0.001
learning_time = 60

[plot]
layout = "2x2"
time_window = 30 # s
dt = 0.01 # s
size = [14, 8] # inches
padding = 5

[plot."(0,0)"]
x = "time"
y = ["fx", "fy", "fz", "pred_0", "pred_1", "pred_2"]
colors = ["red", "green", "blue", "purple", "black", "yellow"]
xlabel = "time (s)"
ylabel = "force (N)"
limits = [-3, 3]
title = "force"
n_ticks = 12

[plot."(1,0)"]
x = "time"
y = ["mx", "my", "mz", "pred_3", "pred_4", "pred_5"]
colors = ["red", "green", "blue", "purple", "black", "yellow"]
xlabel = "time (s)"
ylabel = "torque (Nm)"
limits = [-1, 1]
title = "torque"
n_ticks = 5

[plot."(:,1)"]
x = "time"
y = ["s0", "s1", "s2", "s3"]
xlabel = "time (s)"
ylabel = "value (%)"
colors = ["red", "green", "blue", "yellow"]
limits = [-30, 30]
title = "values"
n_ticks = 30

