[server]
ip = "auto"
port = 8080
timeout = 2

[client]
ip = "145.94.162.95"
port = 8080
control = true

[data]
save = true
path = "data/"
date_format = "%d-%m-%Y_%H-%M-%S"

[figure]
save = false
path = "figures/"
format = "png"
date_format = "%d-%m-%Y_%H-%M-%S"

[colors]
red = "#cf7171"
green = "#dbe8c1"
blue = "#aecdd2"
yellow = "#fadf7f"
purple = "#c696bc"
black = "#4d5359"

[model]
targets = ["fx", "fy", "fz"]
features = ["s0", "s1", "s2", "s3"]
required_samples = 128
max_samples = 512
epochs = 20
batch_size = 32
lr = 0.001
learning_time = 30
model = "multi_head_fnn"
single_model = true
tau = 0.1

[model.hyperparameters]
hidden_dims = [64, 64]
dropout = 0.2
# n_inducing_points = 32
# kernel = "rq"
# mean = "constant"

[plot]
layout = "3x2"
time_window = 30 # s
dt = 0.01 # s
size = [14, 8] # inches
padding = 5

[plot."(0,0)"]
x = "time"
y = ["fx", "fx_pred"]
colors = ["red", "black"]
xlabel = "time (s)"
ylabel = "force (N)"
limits = [-3, 3]
title = "force"
n_ticks = 12

[plot."(1,0)"]
x = "time"
y = ["fy", "fy_pred"]
colors = ["green", "black"]
xlabel = "time (s)"
ylabel = "force (N)"
limits = [-3, 3]
title = "force"
n_ticks = 12

[plot."(2,0)"]
x = "time"
y = ["fz", "fz_pred"]
colors = ["blue", "black"]
xlabel = "time (s)"
ylabel = "force (N)"
limits = [-3, 3]
title = "force"
n_ticks = 12

[plot."(:,1)"]
x = "time"
y = ["s0", "s1", "s2", "s3"]
xlabel = "time (s)"
ylabel = "value (%)"
colors = ["red", "green", "blue", "yellow"]
limits = [-30, 30]
title = "values"
n_ticks = 30


