.ONESHELL:
SHELL := /bin/bash

run:
	clear && python3 main.py --command run

home:
	clear && python3 main.py --command home

read:
	clear && python3 main.py --command read

steps:
	clear && python3 main.py --command steps

.PHONY: run home read
