.ONESHELL:
SHELL := /bin/bash

dataset:
	clear && python3 dataset.py

home:
	clear && python3 home.py

read:
	clear && python3 read.py

control:
	clear && python3 control.py

.PHONY: dataset home read
